/**
 * ============================================================
 * Frontend File Generator (Steps 5–7)
 * ============================================================
 * Generates auth service, apiClient, useAuth hook, and AuthContext
 * All files use the detected frontend extension and exact backend routes
 * ============================================================
 */

import { DetectedRoute } from "./backendRouteDetector.js";

export interface GeneratedFile {
  relativePath: string;
  content: string;
}

/**
 * Generate all frontend integration files
 */
export function generateFrontendFiles(
  ext: string,
  routes: DetectedRoute[],
  backendUrl: string
): GeneratedFile[] {
  const isTs = ext === ".ts" || ext === ".tsx";
  const files: GeneratedFile[] = [];

  files.push(generateApiClient(ext, backendUrl, isTs));
  files.push(generateAuthService(ext, routes, isTs));
  files.push(generateAuthHook(ext, routes, isTs));
  files.push(generateAuthContext(ext, routes, isTs));

  return files;
}

/**
 * Step 6 — Generate src/utils/apiClient.{ext}
 */
function generateApiClient(ext: string, backendUrl: string, isTs: boolean): GeneratedFile {
  const content = `/**
 * Auto-generated by Auth-Gen
 * Axios client configured with backend base URL
 */

import axios from "axios";

const apiClient = axios.create({
  baseURL: "${backendUrl}",
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
});

// Attach JWT token to every request if available
apiClient.interceptors.request.use((config${isTs ? ": any" : ""}) => {
  const token = localStorage.getItem("token");
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`;
  }
  return config;
});

// Handle 401 responses globally
apiClient.interceptors.response.use(
  (response${isTs ? ": any" : ""}) => response,
  (error${isTs ? ": any" : ""}) => {
    if (error.response && error.response.status === 401) {
      localStorage.removeItem("token");
    }
    return Promise.reject(error);
  }
);

export default apiClient;
`;

  return { relativePath: `src/utils/apiClient${ext}`, content };
}

/**
 * Step 5 — Generate src/services/auth.{ext}
 * Uses EXACT detected backend routes — never hardcoded
 */
function generateAuthService(ext: string, routes: DetectedRoute[], isTs: boolean): GeneratedFile {
  const registerRoute = routes.find((r) => r.purpose === "register");
  const loginRoute = routes.find((r) => r.purpose === "login");
  const logoutRoute = routes.find((r) => r.purpose === "logout");
  const userRoute = routes.find((r) => r.purpose === "user");

  const anyType = isTs ? ": any" : "";

  let content = `/**
 * Auto-generated by Auth-Gen
 * Authentication API service — uses exact backend routes
 */

import apiClient from "../utils/apiClient";
`;

  if (registerRoute) {
    content += `
/**
 * Register a new user
 * Route: ${registerRoute.method} ${registerRoute.path}
 */
export const register = (data${anyType}) => {
  return apiClient.${registerRoute.method.toLowerCase()}("${registerRoute.path}", data);
};
`;
  }

  if (loginRoute) {
    content += `
/**
 * Login user
 * Route: ${loginRoute.method} ${loginRoute.path}
 */
export const login = (data${anyType}) => {
  return apiClient.${loginRoute.method.toLowerCase()}("${loginRoute.path}", data);
};
`;
  }

  if (logoutRoute) {
    content += `
/**
 * Logout user
 * Route: ${logoutRoute.method} ${logoutRoute.path}
 */
export const logout = () => {
  return apiClient.${logoutRoute.method.toLowerCase()}("${logoutRoute.path}");
};
`;
  } else {
    content += `
/**
 * Logout user (client-side token removal)
 */
export const logout = () => {
  localStorage.removeItem("token");
};
`;
  }

  if (userRoute) {
    content += `
/**
 * Get users (requires authentication)
 * Route: ${userRoute.method} ${userRoute.path}
 */
export const getUsers = () => {
  return apiClient.${userRoute.method.toLowerCase()}("${userRoute.path}");
};
`;
  }

  return { relativePath: `src/services/auth${ext}`, content };
}

/**
 * Step 7 — Generate src/hooks/useAuth.{ext}
 */
function generateAuthHook(ext: string, routes: DetectedRoute[], isTs: boolean): GeneratedFile {
  const hasRegister = routes.some((r) => r.purpose === "register");
  const hasLogin = routes.some((r) => r.purpose === "login");

  const imports: string[] = [];
  if (hasLogin) imports.push("login");
  if (hasRegister) imports.push("register");
  imports.push("logout");

  const anyType = isTs ? ": any" : "";

  const content = `/**
 * Auto-generated by Auth-Gen
 * Authentication hook for frontend components
 */

import { ${imports.join(", ")} } from "../services/auth";

export function useAuth() {
${hasLogin ? `
  const loginUser = async (data${anyType}) => {
    const response = await login(data);
    if (response.data && response.data.token) {
      localStorage.setItem("token", response.data.token);
    }
    return response.data;
  };
` : ""}
${hasRegister ? `
  const registerUser = async (data${anyType}) => {
    const response = await register(data);
    if (response.data && response.data.token) {
      localStorage.setItem("token", response.data.token);
    }
    return response.data;
  };
` : ""}
  const logoutUser = () => {
    logout();
    localStorage.removeItem("token");
  };

  const getToken = () => {
    return localStorage.getItem("token");
  };

  const isAuthenticated = () => {
    return !!localStorage.getItem("token");
  };

  return {
${hasLogin ? "    loginUser,\n" : ""}${hasRegister ? "    registerUser,\n" : ""}    logoutUser,
    getToken,
    isAuthenticated,
  };
}
`;

  return { relativePath: `src/hooks/useAuth${ext}`, content };
}

/**
 * Generate src/context/AuthContext.{ext}
 */
function generateAuthContext(ext: string, routes: DetectedRoute[], isTs: boolean): GeneratedFile {
  const isReact = ext === ".tsx" || ext === ".jsx";
  const hasRegister = routes.some((r) => r.purpose === "register");
  const hasLogin = routes.some((r) => r.purpose === "login");

  if (!isReact) {
    const content = `/**
 * Auto-generated by Auth-Gen
 * Simple auth state management (non-React)
 */

let currentUser = null;

export function setUser(user${isTs ? ": any" : ""}) {
  currentUser = user;
}

export function getUser() {
  return currentUser;
}

export function clearUser() {
  currentUser = null;
  localStorage.removeItem("token");
}
`;
    return { relativePath: `src/context/AuthContext${ext}`, content };
  }

  const content = `/**
 * Auto-generated by Auth-Gen
 * React Authentication Context
 */

import { createContext, useContext, useState, useEffect${isTs ? ", ReactNode" : ""} } from "react";
import { useAuth } from "../hooks/useAuth";

${isTs ? `interface AuthContextType {
  user: any;
  token: string | null;
  isAuthenticated: boolean;
${hasLogin ? "  loginUser: (data: any) => Promise<any>;\n" : ""}${hasRegister ? "  registerUser: (data: any) => Promise<any>;\n" : ""}  logoutUser: () => void;
}

interface AuthProviderProps {
  children: ReactNode;
}
` : ""}
const AuthContext = createContext${isTs ? "<AuthContextType | null>" : ""}(null);

export function AuthProvider({ children }${isTs ? ": AuthProviderProps" : ""}) {
  const [user, setUser] = useState${isTs ? "<any>" : ""}(null);
  const [token, setToken] = useState${isTs ? "<string | null>" : ""}(localStorage.getItem("token"));
  const auth = useAuth();

  useEffect(() => {
    const savedToken = localStorage.getItem("token");
    if (savedToken) {
      setToken(savedToken);
    }
  }, []);
${hasLogin ? `
  const handleLogin = async (data${isTs ? ": any" : ""}) => {
    const result = await auth.loginUser(data);
    if (result.token) {
      setToken(result.token);
      setUser(result.user);
    }
    return result;
  };
` : ""}
${hasRegister ? `
  const handleRegister = async (data${isTs ? ": any" : ""}) => {
    const result = await auth.registerUser(data);
    if (result.token) {
      setToken(result.token);
      setUser(result.user);
    }
    return result;
  };
` : ""}
  const handleLogout = () => {
    auth.logoutUser();
    setUser(null);
    setToken(null);
  };

  return (
    <AuthContext.Provider
      value={{
        user,
        token,
        isAuthenticated: !!token,
${hasLogin ? "        loginUser: handleLogin,\n" : ""}${hasRegister ? "        registerUser: handleRegister,\n" : ""}        logoutUser: handleLogout,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}

export function useAuthContext() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuthContext must be used within an AuthProvider");
  }
  return context;
}

export default AuthContext;
`;

  return { relativePath: `src/context/AuthContext${ext}`, content };
}
