/**
 * ============================================================
 * Environment File Generator
 * ------------------------------------------------------------
 * Generates secure .env file with random JWT secret
 * ============================================================
 */

import fs from "fs-extra";
import path from "path";
import crypto from "crypto";
import chalk from "chalk";

/**
 * Generate a cryptographically secure random string
 * @param length - Length of the random string
 */
function generateSecret(length: number = 64): string {
    return crypto.randomBytes(length).toString("hex");
}

/**
 * Create .env file in project with generated secrets
 * @param projectPath - Absolute path to the project
 * @param database - Database type (sqlite, postgres, mysql, mongodb)
 */
export async function generateEnvFile(
    projectPath: string,
    database: string
): Promise<void> {
    const envPath = path.join(projectPath, ".env");

    // Generate secure JWT secret
    const jwtSecret = generateSecret(64);

    // Base environment variables
    let envContent = `# Auto-generated by Auth-Gen
# Generated on: ${new Date().toISOString()}

# Server Configuration
PORT=5000
NODE_ENV=development

# JWT Configuration
JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=1h

`;

    // Add database-specific configuration
    switch (database.toLowerCase()) {
        case "sqlite":
            envContent += `# SQLite Configuration
DB_PATH=./database.sqlite
`;
            break;

        case "postgres":
        case "postgresql":
            envContent += `# PostgreSQL Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=auth_db
DB_USER=postgres
DB_PASSWORD=your_password_here
DB_SSL=false
`;
            break;

        case "mysql":
            envContent += `# MySQL Configuration
DB_HOST=localhost
DB_PORT=3306
DB_NAME=auth_db
DB_USER=root
DB_PASSWORD=your_password_here
`;
            break;

        case "mongodb":
            envContent += `# MongoDB Configuration
MONGODB_URI=mongodb://localhost:27017/auth_db
`;
            break;
    }

    // Write .env file
    await fs.writeFile(envPath, envContent, "utf-8");
    console.log(chalk.green(`✅ Created .env file with secure JWT secret`));
}
