/**
 * ============================================================
 * Express + SQLite Authentication Server
 * ------------------------------------------------------------
 * Production-ready authentication backend
 * Generated by Auth-Gen
 * ============================================================
 */

import express, { Request, Response, NextFunction } from "express";
import dotenv from "dotenv";
import helmet from "helmet";
import authRoutes from "./routes/auth";
import { initDb } from "./utils/db";

// Load environment variables
dotenv.config();

// Initialize Express app
const app = express();
const PORT = process.env.PORT || 5000;

/**
 * ==========================================
 * MIDDLEWARE
 * ==========================================
 */

import cors from "cors";

// Security middleware
app.use(helmet());
app.use(cors()); // Allow all origins for development

// Body parsing middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Request logging middleware (development only)
if (process.env.NODE_ENV === "development") {
  app.use((req: Request, res: Response, next: NextFunction) => {
    console.log(`${req.method} ${req.path}`);
    next();
  });
}

/**
 * ==========================================
 * ROUTES
 * ==========================================
 */

// Health check endpoint
app.get("/health", (req: Request, res: Response) => {
  res.json({
    status: "ok",
    message: "Server is running",
    timestamp: new Date().toISOString(),
  });
});

// Authentication routes
app.use("/api", authRoutes);

// 404 handler
app.use((req: Request, res: Response) => {
  res.status(404).json({
    error: "Route not found",
    path: req.path,
  });
});

// Error handling middleware
app.use((err: Error, req: Request, res: Response, next: NextFunction) => {
  console.error("Error:", err);
  res.status(500).json({
    error: "Internal server error",
    message: process.env.NODE_ENV === "development" ? err.message : undefined,
  });
});

/**
 * ==========================================
 * SERVER INITIALIZATION
 * ==========================================
 */

// Initialize database and start server
initDb()
  .then(() => {
    app.listen(PORT, () => {
      console.log(`\n🚀 Server running on http://localhost:${PORT}`);
      console.log(`📊 Database: SQLite (database.sqlite)`);
      console.log(`🔒 Security: Helmet enabled`);
      console.log(`\n📚 Available endpoints:`);
      console.log(`  POST   /api/signup     - Register new user`);
      console.log(`  POST   /api/login      - Login user`);
      console.log(`  GET    /api/users      - Get all users (requires auth)`);
      console.log(`  GET    /health         - Health check\n`);
    });
  })
  .catch((err) => {
    console.error("❌ Failed to initialize database:", err);
    process.exit(1);
  });

// Graceful shutdown
process.on("SIGTERM", () => {
  console.log("\n⏳ SIGTERM signal received: closing HTTP server");
  process.exit(0);
});

process.on("SIGINT", () => {
  console.log("\n⏳ SIGINT signal received: closing HTTP server");
  process.exit(0);
});
